### ISSUE TITLE
Please make 2.1 plugins available

### ISSUE THREAD

**Issue by continentalop99** [azkaban/azkaban.github.io#9]
Hello,

 I have a group of users that are still using version 2.1 and would like the plugins installed but I can not find the 2.1 plugins available for download.  Can you please make the 2.1 plugins available for download again.  

David Chen suggested I submit this issue here.

thanks you
Jeanne Greulich

**Comment by HappyRay** [comment]
Can you build it from source?
Pls reopen if you still need help.
